apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-api-sa
  namespace: llmops
  annotations:
    # Workload Identity — maps this SA to mi-rag-api-prod managed identity
    # Client ID from terraform output: rag_api_client_id
    azure.workload.identity/client-id: "87c2c4e4-3998-4798-a9fa-1d22dc63c49a"
  labels:
    azure.workload.identity/use: "true"