executor: "KubernetesExecutor"

fernetKeySecretName: airflow-fernet-key

tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"

env:
  - name: AIRFLOW__CORE__PARALLELISM
    value: "10"
  - name: AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG
    value: "10"
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "False"
  - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
    value: "False"

extraEnv: |
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: ingestion-secrets
        key: POSTGRES_HOST
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: ingestion-secrets
        key: POSTGRES_USER
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ingestion-secrets
        key: POSTGRES_PASSWORD
  - name: AZURE_STORAGE_ACCOUNT
    valueFrom:
      secretKeyRef:
        name: ingestion-secrets
        key: AZURE_STORAGE_ACCOUNT

workers:
  replicas: 0

redis:
  enabled: false

webserver:
  replicas: 1
  service:
    type: ClusterIP

scheduler:
  replicas: 1

triggerer:
  replicas: 1

postgresql:
  enabled: false

data:
  metadataSecretName: airflow-db-secret

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: false

logs:
  persistence:
    enabled: false
webserverSecretKeySecretName: airflow-webserver-secret
